load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "math_constants",
    hdrs = ["math_constants.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "time_constants",
    hdrs = ["time_constants.h"],
    visibility = ["//visibility:public"],
)
