filegroup(
    name = "cube",
    srcs = [
        "cube.mtl",
        "cube.obj",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "textured_cube",
    srcs = [
        "textured_cube.mtl",
        "textured_cube.obj",
        "textured_cube.png",
    ],
    visibility = ["//visibility:public"],
)
