load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ecs",
    hdrs = [
        "ecs.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//sw_renderer:stl",
    ],
)
