load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "fixed_point",
    hdrs = [
        "fixed_point.h",
        "int128.h",
        "math.h",
        "operations.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["@fmt"],
)
